# Generated by Django 4.2.7 on 2023-11-13 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(blank=True, default=None)),
                ('primary_issue', models.TextField(default=None)),
                ('date_entered', models.DateField(auto_now_add=True)),
                ('under_warranty', models.BooleanField(default=False)),
                ('charges', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer')),
                ('spa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customerspa')),
            ],
        ),
    ]
