# Generated by Django 4.2.7 on 2023-11-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(default=0.0)),
                ('tax', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_paid', models.DateField(blank=True, default=None, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(default=None, max_length=200)),
                ('part_number', models.CharField(default=None, max_length=100)),
                ('part_description', models.TextField(default=None)),
                ('part_cost', models.FloatField(default=0.0)),
                ('part_price', models.FloatField(default=0.0)),
                ('is_discontinued', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(blank=True, default=None)),
                ('primary_issue', models.TextField(default=None)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('num_visits', models.IntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
                ('date_completed', models.DateField(blank=True, default=None, null=True)),
                ('under_warranty', models.BooleanField(default=False)),
                ('upfront_charges', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer')),
                ('spa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customerspa')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_scheduled', models.DateTimeField(blank=True, default=None, null=True)),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.serviceticket')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.invoice')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.partslist')),
            ],
        ),
    ]
