# Generated by Django 4.2.7 on 2023-11-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='service_ticket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service.serviceticket'),
            preserve_default=False,
        ),
    ]
