# Generated by Django 4.2.7 on 2023-11-13 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(default=0.0)),
                ('tax', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_paid', models.DateField(blank=True, default=None, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(default=None, max_length=200)),
                ('part_number', models.CharField(default=None, max_length=100)),
                ('part_description', models.TextField(default=None)),
                ('part_cost', models.FloatField(default=0.0)),
                ('part_price', models.FloatField(default=0.0)),
                ('is_discontinued', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='serviceticket',
            old_name='charges',
            new_name='upfront_charges',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='date_completed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='num_visits',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_scheduled', models.DateTimeField(blank=True, default=None, null=True)),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.serviceticket')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.invoice')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.partslist')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service.serviceticket'),
        ),
    ]
