# Generated by Django 4.2.7 on 2023-11-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('service', '0002_invoice_service_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='technician',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.internaluser'),
            preserve_default=False,
        ),
    ]
