# Generated by Django 4.2.7 on 2023-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceticket_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='adjusted_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
