# Generated by Django 4.2.7 on 2023-11-13 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default=None, max_length=200)),
                ('contact_first', models.CharField(default=None, max_length=100)),
                ('contact_last', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('contact_phone', models.CharField(default=None, max_length=12)),
                ('contact_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address1', models.CharField(default=None, max_length=200)),
                ('address2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('intersection_note', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('customer_since', models.IntegerField(default=2023, max_length=4)),
                ('customer_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spa_make', models.CharField(default=None, max_length=200)),
                ('spa_model', models.CharField(default=None, max_length=100)),
                ('spa_subpanel', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('water_system', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('installed_date', models.DateField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.customer')),
            ],
        ),
    ]
